// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LampState.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_LAMPSTATE_H_
#define _FAST_DDS_GENERATED_LAMPSTATE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/optional.hpp>



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(LAMPSTATE_SOURCE)
#define LAMPSTATE_DllAPI __declspec( dllexport )
#else
#define LAMPSTATE_DllAPI __declspec( dllimport )
#endif // LAMPSTATE_SOURCE
#else
#define LAMPSTATE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define LAMPSTATE_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



/*!
 * @brief This class represents the structure LampState defined by the user in the IDL file.
 * @ingroup LampState
 */
class LampState
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport LampState();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~LampState();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object LampState that will be copied.
     */
    eProsima_user_DllExport LampState(
            const LampState& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object LampState that will be copied.
     */
    eProsima_user_DllExport LampState(
            LampState&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object LampState that will be copied.
     */
    eProsima_user_DllExport LampState& operator =(
            const LampState& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object LampState that will be copied.
     */
    eProsima_user_DllExport LampState& operator =(
            LampState&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x LampState object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const LampState& x) const;

    /*!
     * @brief Comparison operator.
     * @param x LampState object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const LampState& x) const;

    /*!
     * @brief This function copies the value in member LampID
     * @param _LampID New value to be copied in member LampID
     */
    eProsima_user_DllExport void LampID(
            const eprosima::fastcdr::fixed_string<16>& _LampID);

    /*!
     * @brief This function moves the value in member LampID
     * @param _LampID New value to be moved in member LampID
     */
    eProsima_user_DllExport void LampID(
            eprosima::fastcdr::fixed_string<16>&& _LampID);

    /*!
     * @brief This function returns a constant reference to member LampID
     * @return Constant reference to member LampID
     */
    eProsima_user_DllExport const eprosima::fastcdr::fixed_string<16>& LampID() const;

    /*!
     * @brief This function returns a reference to member LampID
     * @return Reference to member LampID
     */
    eProsima_user_DllExport eprosima::fastcdr::fixed_string<16>& LampID();


    /*!
     * @brief This function sets a value in member on
     * @param _on New value for member on
     */
    eProsima_user_DllExport void on(
            bool _on);

    /*!
     * @brief This function returns the value of member on
     * @return Value of member on
     */
    eProsima_user_DllExport bool on() const;

    /*!
     * @brief This function returns a reference to member on
     * @return Reference to member on
     */
    eProsima_user_DllExport bool& on();

private:

    eprosima::fastcdr::fixed_string<16> m_LampID;
    bool m_on{false};

};

#endif // _FAST_DDS_GENERATED_LAMPSTATE_H_

